spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
    generate-ddl: true

  sql:
    init:
      mode: always
      platform: h2

  mvc:
    hiddenmethod:
      filter:
        enabled: true

bookDaysToExpired: 10

#  profiles:
#    active: dev

server:
  port: 8080