spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/librarian-v2
    username: postgres
    password: 1Parolef*

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false
    generate-ddl: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

bookDaysToExpired: 30

server:
  port: 8080