CREATE TABLE person (
                        id bigint generated by default as identity primary key unique ,
                        full_name varchar(100) UNIQUE NOT NULL ,
                        login varchar (100) UNIQUE NOT NULL ,
                        password varchar (100) NOT NULL ,
                        email varchar (100) UNIQUE NOT NULL,
                        year_of_birth date NOT NULL,
                        person_role varchar (20),
                        is_baned boolean not null ,
                        pass_expired boolean not null
);

CREATE TABLE book (
                      id bigint generated by default as identity primary key ,
                      name varchar(100) not null ,
                      author varchar(100)  not null ,
                      "year" varchar not null ,
                      books_count bigint not null
);

CREATE TABLE person_book (
                             id bigint generated by default as identity primary key unique ,
                             person_book_date date not null ,
                             book bigint references book(id) on delete RESTRICT not null ,
                             person bigint references person(id) on delete RESTRICT not null
);

insert into person (full_name, login, password, email, year_of_birth, person_role, is_baned, pass_expired)
values  ('Админ Админович Админов', 'admin', '$2a$10$DlFeQQyrMOxyh8r6ZOwMy.44e4.Pl5DjapV2V75F8qp3LVaM.3lfC', 'admin@adminovich.com', '2021-07-05', 'ADMIN', false, false),
        ('Юзер Юзерович Один', 'user', '$2a$10$Hw74MFCP8YgX.ShD3Us3eeltUHdS9EjKxMXZ.y9VGXZ6J8au8DVKi', 'user@user.com', '2019-07-01', 'USER', false, false),
        ('Юзер Юзерович Два', 'user2', '$2a$10$wyTIwEFqi5CqwfOniFmgw.sAwbXIXrtQwAJDYgJidSHKnXcxv4QDu', 'user2@user2.com', '2019-07-08', 'USER', false, false),
        ('Юзер Юзерович Три', 'user3', '$2a$10$lm0X4hRrPFtcJ/30vta9Ee.ccprguQrC0dhM8sD3ejbZ2fmrwCNBi', 'user3@user3.com', '2017-07-02', 'USER', false, false),
        ('Менеджер Менеджерович Менеджеров', 'manager', '$2a$10$6YpthYF0RwOJzS7c4rSHeOy/c5eCd3B4dQ009EVJd1hn9IZVwOJha', 'manager@manager.com', '2018-07-17', 'MANAGER', false, false),
        ('Бан Баннович Баннанов', 'banned', '$2a$10$ntaE4CfRP9kPQcXq2HL8se8NP31gxLS2jRrZXuH0b0b53Sv1YBOOm', 'banned@banned.com', '2017-07-12', 'USER', true, false),
        ('Менеджер Менеджероч Второй', 'manager2', '$2a$10$k/dLJvGSYevBYHQ6bdEJueQ/iUu3KqBY7gqSzHMmbtu8e9IJVbqlO', 'manager2@manager2.com', '2019-03-06', 'MANAGER', true, false);

insert into book (name, author, "year", books_count)
values ('Мастер и Маргарита', 'Михаил Булгаков', '1929', 7),
       ('Собачье сердце', 'Михаил Булгаков', '1925', 5),
       ('Двенадцать стульев', 'Илья Ильф, Евгений Петров', '1928', 5),
       ('Мёртвые души', 'Николай Гоголь', '1842', 7),
       ('Граф Монте-Кристо', 'Александр Дюма', '1844', 5),
       ('Золотой теленок', 'Илья Ильф, Евгений Петров', '1931', 9),
       ('Три товарища', 'Эрих Мария Ремарк', '1936', 8),
       ('Отверженные', 'Виктор Гюго', '1862', 9),
       ('Евгений Онегин', 'Александр Пушкин', '1825', 10),
       ('Преступление и наказание', 'Федор Достоевский', '1866', 10),
       ('Война и мир', 'Лев Толстой', '1865', 9),
       ('Повести Белкина', 'Александр Пушкин', '1831', 9),
       ('Ревизор', 'Николай Гоголь', '1836', 10),
       ('Село Степанчиково и его обитатели', 'Федор Достоевский', '1859', 10),
       ('Отцы и дети', 'Иван Тургенев', '1860', 9),
       ('Три мушкетера', 'Александр Дюма', '1844', 8),
       ('Палата № 6', 'Антон Чехов', '1892', 9),
       ('Братья Карамазовы', 'Федор Достоевский', '1879', 9),
       ('Собака Баскервилей', 'Артур Конан Дойль', '1901', 0),
       ('Идиот', 'Федор Достоевский', '1868', 0),
       ('Приключения Джуна в России', 'Джун Джунович Джунов', '2022-2023', 9),
       ('Работодать ты где или как приручить ЭЙЧАР', 'Джун Джунович Джунов', '2023', 9);


insert into person_book (person_book_date, book, person)
values  ('2023-07-07', 16, 2),
        ('2023-07-07', 3, 2),
        ('2023-07-07', 7, 2),
        ('2023-07-07', 20, 2),
        ('2023-07-07', 16, 3),
        ('2023-07-07', 15, 3),
        ('2023-07-07', 2, 3),
        ('2023-07-07', 19, 3),
        ('2023-01-03', 17, 4),
        ('2023-05-27', 12, 4),
        ('2023-07-10', 18, 4),
        ('2023-07-10', 5, 2),
        ('2023-07-10', 11, 2),
        ('2023-01-01', 21, 2),
        ('2023-01-01', 22, 2);