drop table person_book;
drop table person;
drop table book;

CREATE TABLE person (
                        id bigint generated by default as identity primary key unique ,
                        full_name varchar(100) UNIQUE NOT NULL ,
                        "login" varchar (100) UNIQUE NOT NULL ,
                        "password" varchar (100) NOT NULL ,
                        email varchar (100) UNIQUE NOT NULL,
                        year_of_birth date NOT NULL,
                        person_role varchar (20),
                        is_baned boolean not null ,
                        pass_expired boolean not null
);

CREATE TABLE book (
                      id bigint generated by default as identity primary key ,
                      "name" varchar(100) not null ,
                      author varchar(100)  not null ,
                      "year" varchar not null ,
                      books_count bigint not null
);


CREATE TABLE person_book (
                             id bigint generated by default as identity primary key unique ,
                             person_book_date date not null ,
                             book bigint references book(id) on delete RESTRICT,
                             person bigint references person(id) on delete RESTRICT
);